export default  {
    MIN_LEAF_SIZE: 12,
    MAX_LEAF_SIZE: 20,
    MIN_ELLIPSE_RADIUS: 7,
    MAX_ELLIPSE_RADIUS: 12,
    MIN_INTERNAL_CAVES: 1,
    MAX_INTERNAL_CAVES: 10,
    MAP_MARGINS: 2,
    PERCENT_CHANCE_WINDOW: 0.3,
    MAX_AIRLOCK_WINDOWS: 5,
    ASTEROID_SECTION_COUNT: 50,
    ASTEROID_MAP_MARGINS: 1
}